export const ACTIONS = {
  ADD_POSTS: 'ADD_POSTS',
  SET_OFFSET: 'SET_OFFSET',
  CLEAR_STATE: 'CLEAR_STATE',
  POST: 'POST',
  CHANGE_IS_DARK: 'CHANGE_IS_DARK',
  CHANGE_ACTIVE_NAV_BAR: 'CHANGE_ACTIVE_NAV_BAR',
}
